version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.12
    commands:
      - npm install --no-audit --no-fund
  build:
    commands:
      - echo "== Stage: Deploy to Prod (after manual approval) =="
      - npx sls deploy --stage prod --verbose

artifacts:
  files:
    - '**/*'
  base-directory: '.'
